name: Build

on:
  push:
    tags: [ "**" ]
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Project
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: Export Settings
      run: |
        VERSION=$(grep -oP '<Version>\K[^<]+' ${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: v${{ env.VERSION }}
        draft: true

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: publish/${{ github.event.repository.name }}.dll
        asset_name: ${{ github.event.repository.name }}.dll
        asset_content_type: application/octet-stream

    - name: Upload Nuget
      continue-on-error: true
      run: dotnet nuget push **\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
